from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', views.tablero, name='tablero'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('update_us/<int:id>',views.update_us,name="update-us"),
    path('retrieve_user/',views.retrieve_user,name="retrieve_user"),
    path('add_members/<int:id>', views.add_members, name="add-members"),
    path('add_miembros/<int:id>', views.add_miembros, name="add-miembros"),
    path('projects', views.all_projects, name="list-projects"),
    path('log_project/<int:id_proyecto>', views.log_project, name="log-project"),
    path('add_project', views.add_project, name='add-project'),
    path('action_project/<int:id>', views.action_project, name="action-project"),
    path('action_sprint/<int:id_proyecto>/<int:id_sprint>', views.action_sprint, name="action-sprint"),
    path('delete_proyecto/<int:id>', views.delete_proyecto, name='delete-project'),
    path('update_project/<int:id>', views.update_project, name='update-project'),
    path('inicializar_proyecto/<int:id>', views.inicializar_proyecto, name='inicializar_proyecto'),
    path('cancelar_proyecto/<int:id>', views.cancelar_proyecto, name='cancelar_proyecto'),
    path('finalizar_proyecto/<int:id>', views.finalizar_proyecto, name='finalizar_proyecto'),
    path('inicializar_sprint/<int:id_proyecto>/<int:id_sprint>', views.inicializar_sprint, name='inicializar_sprint'),
    path('cancelar_sprint/<int:id_proyecto>/<int:id_sprint>', views.cancelar_sprint, name='cancelar_sprint'),
    path('finalizar_sprint/<int:id_proyecto>/<int:id_sprint>', views.finalizar_sprint, name='finalizar_sprint'),
    path('update_members_project/<int:id_proyecto>/<int:id_miembro>', views.update_members_project, name='update-members_project'),
    path('update_members_sprint/<int:id_proyecto>/<int:id_sprint>/<int:id_usuario>', views.update_members_sprint, name='update-members_sprint'),
    path('roles/<int:id_proyecto>', views.all_roles, name="list-roles"),
    path('list_permisos/<int:id_proyecto>/<int:id_rol>', views.list_permisos, name='list_permisos'),
    path('exportar_rol/<int:id_proyecto>', views.export_roles, name="exportar-roles"),
    path('importar_rol/<int:id_proyecto>', views.import_roles, name="importar-roles"),
    path('add_rol/<int:id_proyecto>', views.add_rol, name='add-rol'),
    path('update_rol/<int:id>/<int:id_proyecto>', views.update_rol, name='update-rol'),
    path('delete_rol/<int:id>/<int:id_proyecto>', views.delete_rol, name='delete-rol'),
    path('delete_miembro/<int:id>/<int:id_proyecto>', views.delete_miembro_proyecto, name='delete-members_project'),
    path('add_members_sprint/<int:id_proyecto>/<int:id_sprint>', views.add_members_sprint, name="add-members-sprint"),
    path('add_miembros_sprint/<int:id_proyecto>/<int:id_sprint>', views.add_miembros_sprint, name="add-miembros-sprint"),
    path('sprint/<int:id>', views.all_sprints, name="sprint-list"),
    path('log_sprint/<int:id_proyecto>/<int:id_sprint>', views.log_sprint, name="log-sprint"),
    path('product_backlog_sprint/<int:id_proyecto>/<int:id_sprint>', views.product_backlog_sprint, name="product-backlog-sprint"),
    path('all_user_story_sprint_backlog/<int:id>', views.all_user_story_sprint_backlog,name="user_story_sprint_backlog-list"),
    path('add_sprint/<int:id>', views.add_sprint, name='add-sprint'),
    path('update_sprint/<int:id_proyecto>/<int:id_sprint>', views.update_sprint, name='update-sprint'),
    path('user_story/<int:id>', views.all_user_story, name="user_story-list"),
    path('add_user_story/<int:id_proyecto>', views.add_user_story, name='add-user_story'),
    path('update_user_story/<int:id_proyecto>/<int:id_user_story>', views.update_user_story, name='update-user_story'),
    path('update_sprint_user_story/<int:id_proyecto>/<int:id_user_story>/<int:id_sprint>', views.update_sprint_user_story, name='update-sprint-user-story'),
    path('update-prioridad-user_story/<int:id_proyecto>/<int:id_user_story>', views.update_prioridad_user_story, name='update-prioridad-user_story'),
    path('tipos_us/<int:id_proyecto>', views.all_tipos_us, name="tipos_us-list"),
    path('export_tipos_us/<int:id_proyecto>', views.export_tipoUS, name="tipos_us-export"),
    path('import_tipos_us/<int:id_proyecto>', views.import_tipo_us, name="tipos_us-import"),
    path('add_tipos_us/<int:id>', views.add_tipos_us, name='add-tipos_us'),
    path('update_tipos_us/<int:id_proyecto>/<int:id_tipo_us>', views.update_tipos_us, name='update-tipos_us'),
    path('delete_tipos_us/<int:id>/<int:id_proyecto>', views.delete_tipo_us, name='delete-tipos_us'),
    # path('asignar_estados_tipos_us/<int:id_proyecto>/<int:id_tipo_us>', views.asignar_estados_tipos_us, name='asignar-estados-tipos-us'),
    path('estados/<int:id_proyecto>/<int:id_tipo_us>', views.all_estados, name="estados-list"),
    path('add_estados/<int:id_proyecto>/<int:id_tipo_us>', views.add_estados, name='add-estados'),
    path('update_estados/<int:id_proyecto>/<int:id_tipo_us>/<int:id_estado>', views.update_estados, name='update-estados'),
    path('delete_estado/<int:id>/<int:id_proyecto>/<int:id_tipo_us>', views.delete_estado, name='delete-estados'),
    path('editar_posicion_estado/<int:id_proyecto>/<int:id_tipo_us>/<int:id_estado>', views.editar_posicion_estado, name='editar-posicion-estado'),
    path('burndown/<int:id_proyecto>/<int:id_sprint>', views.burndown, name='burndown'),
    path('tablero_kanban/<int:id_proyecto>/<int:id_tipo_us>', views.tablero_kanban, name='tablero-kanban'),
    path('update_user_story_kanban_avanzar/<int:id_proyecto>/<int:id_user_story>/<int:id_tipo_us>', views.update_user_story_kanban_avanzar, name='update-user-story-kanban-avanzar'),
    path('update_user_story_kanban_atras/<int:id_proyecto>/<int:id_user_story>/<int:id_tipo_us>', views.update_user_story_kanban_atras, name='update-user-story-kanban-atras'),
    path('update_horas_trabajadas/<int:id_proyecto>/<int:id_user_story>/<int:id_sprint>', views.update_horas_trabajadas,name="update-horas-trabajadas"),
]