# Generated by Django 4.1 on 2022-09-26 06:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colum', models.IntegerField()),
                ('fila', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permisos', models.CharField(max_length=30)),
                ('desc_permisos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=30)),
                ('desc_proyecto', models.TextField()),
                ('estado_proyecto', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=11)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_report', models.CharField(max_length=30)),
                ('desc_report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reunion', models.CharField(max_length=30)),
                ('desc_reunion', models.TextField()),
                ('lugar_reunion', models.CharField(max_length=30)),
                ('fecha_reunion', models.DateField()),
                ('hora_reunion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sprint', models.CharField(max_length=30)),
                ('desc_sprint', models.TextField()),
                ('estado_sprint', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Terminado', 'Terminado')], default='Iniciado', max_length=10)),
                ('fecha_inicio', models.DateField(auto_now=True, null=True)),
                ('duracion_dias', models.IntegerField(null=True)),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sprint_b', models.CharField(max_length=30)),
                ('desc_sprint_b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_us', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('contrasena_usuario', models.CharField(max_length=10)),
                ('estado_usuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_us', models.CharField(max_length=30)),
                ('desc_us', models.TextField()),
                ('horas_estimadas', models.IntegerField(null=True)),
                ('prioridad_us', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10)),
                ('encargado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('id_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_rol', models.TextField()),
                ('permisos', models.ManyToManyField(to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('id_rol', models.ManyToManyField(to='account.rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro_Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajo', models.BigIntegerField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Backlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
            ],
        ),
    ]
