# Generated by Django 4.1 on 2022-10-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Planificado', max_length=12),
        ),
    ]
