# Generated by Django 4.1 on 2022-11-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad_restante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='id_tipo_user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story'),
        ),
    ]
