# Generated by Django 4.1 on 2022-09-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='proyecto',
        ),
    ]
