# Generated by Django 4.1 on 2022-10-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='estado',
            field=models.TextField(default='To Do'),
        ),
    ]
