# Generated by Django 4.1 on 2022-11-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='id_tipo_user_story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story'),
        ),
    ]
