# Generated by Django 4.1 on 2022-08-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colum', models.IntegerField()),
                ('fila', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permisos', models.CharField(max_length=30)),
                ('desc_permisos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_report', models.CharField(max_length=30)),
                ('desc_report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reunion', models.CharField(max_length=30)),
                ('desc_reunion', models.TextField()),
                ('lugar_reunion', models.CharField(max_length=30)),
                ('fecha_reunion', models.DateField()),
                ('hora_reunion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sprint', models.CharField(max_length=30)),
                ('desc_sprint', models.TextField()),
                ('estado_sprint', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sprint_b', models.CharField(max_length=30)),
                ('desc_sprint_b', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_us', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_us', models.CharField(max_length=30)),
                ('prioridad_us', models.CharField(max_length=30)),
                ('tipo_us', models.CharField(max_length=30)),
                ('desc_us', models.TextField()),
                ('com_us', models.TextField()),
                ('historial_us', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Backlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
            ],
        ),
    ]
