# Generated by Django 4.0.1 on 2022-10-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados',
            name='id_tipo_user_story',
        ),
        migrations.RemoveField(
            model_name='tipo_user_story',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='estados',
            name='id_tipo_user_story_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_user_story_asignado', to='account.tipo_user_story'),
        ),
        migrations.AddField(
            model_name='estados',
            name='id_tipo_user_story_vinculado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_user_story_vinculado', to='account.tipo_user_story'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='id_rol',
            field=models.ManyToManyField(to='account.Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Planificado', max_length=12),
        ),
    ]
