# Generated by Django 4.1 on 2022-09-29 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_proyectos_scrum_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='scrum_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
