# Generated by Django 4.0.1 on 2022-10-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_userstory_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='id_rol',
            field=models.ManyToManyField(to='account.Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ManyToManyField(blank=True, db_table='estados_tipo_us', to='account.Estados'),
        ),
        migrations.CreateModel(
            name='PerfilImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_imagen', models.ImageField(default='static/perfil.jpg', upload_to='')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
