# Generated by Django 4.1 on 2022-11-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userstory_id_tipo_user_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridad_final',
            field=models.FloatField(default=0),
        ),
    ]
