# Generated by Django 4.0.1 on 2022-10-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_sprint_estado_sprint'),
        ('account', '0002_remove_estados_id_tipo_user_story_and_more'),
    ]

    operations = [
    ]
