# Generated by Django 4.1 on 2022-11-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userstory_estado_definitivo_tareauserstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareauserstory',
            old_name='desc_daily',
            new_name='desc_tarea',
        ),
    ]
