# Generated by Django 4.1 on 2022-09-26 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_remove_userstory_encargado_userstory_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='encargado',
        ),
        migrations.AddField(
            model_name='userstory',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
