# Generated by Django 4.1 on 2022-09-29 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_rol_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos'),
        ),
    ]
