# Generated by Django 4.0.1 on 2022-10-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20221012_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados',
            name='id_tipo_user_story_asignado',
        ),
        migrations.RemoveField(
            model_name='estados',
            name='id_tipo_user_story_vinculado',
        ),
        migrations.AddField(
            model_name='estados',
            name='id_tipo_user_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story'),
        ),
        migrations.AddField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.estados'),
        ),
    ]
