# Generated by Django 4.1 on 2022-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userstory_encargado_userstory_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Planificado', max_length=11),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Iniciado', max_length=12),
        ),
    ]
