# Generated by Django 4.1 on 2022-11-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_desc_daily_tareauserstory_desc_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareauserstory',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
    ]
