# Generated by Django 4.1 on 2022-09-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rol_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_User_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_us', models.CharField(max_length=30)),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.estados')),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
            ],
        ),
        migrations.DeleteModel(
            name='TipoUS',
        ),
        migrations.AddField(
            model_name='estados',
            name='id_tipo_user_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='id_tipo_user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story'),
        ),
    ]
