# Generated by Django 4.0.1 on 2022-10-25 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_alter_miembros_id_rol_alter_rol_permisos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_user_story',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='estados',
            name='posicion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilimagen',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
