# Generated by Django 4.0.1 on 2022-10-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_estados_id_tipo_user_story_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_user_story',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ManyToManyField(blank=True, db_table='estados_tipo_us', null=True, to='account.Estados'),
        ),
    ]
