# Generated by Django 4.1 on 2022-09-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_proyectos_scrum_master'),
        ('account', '0004_estados_tipo_user_story_delete_tipous_and_more'),
    ]

    operations = [
    ]
