# Generated by Django 4.0.1 on 2022-10-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_tipo_user_story_id_estado_estados_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados',
            name='posicion',
        ),
        migrations.AddField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ManyToManyField(blank=True, db_table='estados_tipo_us', to='account.Estados'),
        ),
    ]
