# Generated by Django 4.1 on 2022-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_sprint_capacidad_alter_proyectos_estado_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_sprint',
            name='horas_trabajo',
            field=models.IntegerField(null=True),
        ),
    ]
