# Generated by Django 4.1 on 2022-11-04 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_horas_trabajadas_tareauserstory_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguserstory',
            name='id_user_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userstory'),
        ),
        migrations.AlterField(
            model_name='loguserstory',
            name='fecha_creacion',
            field=models.TextField(null=True),
        ),
    ]
