# Generated by Django 4.0.1 on 2022-10-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_estados_posicion_tipo_user_story_id_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilImagen',
        ),
    ]
