# Generated by Django 4.1 on 2022-09-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_miembro_sprint_horas_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='id_miembro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.miembros'),
        ),
    ]
