# Generated by Django 4.1 on 2022-08-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_miembros_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='id_rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.roles'),
        ),
    ]
