# Generated by Django 4.1 on 2022-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_tipo_user_story_id_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ManyToManyField(blank=True, db_table='estados_tipo_us', to='account.estados'),
        ),
    ]
