# Generated by Django 4.0.1 on 2022-10-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_perfilimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_user_story',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='estados',
            name='posicion',
            field=models.IntegerField(default=0),
        ),
    ]
