# Generated by Django 4.1 on 2022-09-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_proyectos_id_miembro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='id_miembro',
        ),
    ]
