# Generated by Django 4.1 on 2022-12-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_loguserstory_id_user_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='cancelar',
            field=models.TextField(null=True),
        ),
    ]
