# Generated by Django 4.0.1 on 2022-10-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_tipo_user_story_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_user_story',
            name='id_estado',
            field=models.ManyToManyField(blank=True, db_table='estados_tipo_us', to='account.Estados'),
        ),
    ]
