# Generated by Django 4.1 on 2022-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_miembros_id_rol_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='estado_usuario',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
