# Generated by Django 4.0.1 on 2022-10-30 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0007_remove_tipo_user_story_id_estado_estados_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserStory',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_us', models.CharField(max_length=30)),
                ('desc_us', models.TextField()),
                ('horas_estimadas', models.IntegerField(default=0)),
                ('horas_trabajadas', models.IntegerField(default=0)),
                ('prioridad_us', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=10)),
                ('estado', models.TextField(default='To Do')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('id_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sprint')),
                ('id_tipo_user_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_user_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogTipo_User_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('nombre_tipo_us', models.CharField(max_length=30)),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_tipo_user_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogSprint',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sprint', models.CharField(max_length=30)),
                ('desc_sprint', models.TextField()),
                ('estado_sprint', models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Planificado', max_length=12)),
                ('fecha_inicio', models.DateField(auto_now=True, null=True)),
                ('duracion_dias', models.IntegerField(null=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_sprint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_rol', models.TextField()),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('nombre_proyecto', models.CharField(max_length=30)),
                ('desc_proyecto', models.TextField()),
                ('estado_proyecto', models.CharField(choices=[('Planificado', 'Planificado'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Planificado', max_length=11)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogMiembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('id_rol', models.ManyToManyField(to='account.Rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_miembros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogMiembro_Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('horas_trabajo', models.IntegerField(null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_miembro_sprint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_accion', models.CharField(max_length=30)),
                ('nombre_estado', models.CharField(max_length=30)),
                ('posicion', models.IntegerField(default=0)),
                ('id_tipo_user_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tipo_user_story')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsable_estados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
