# Generated by Django 4.0.1 on 2022-10-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_tipo_user_story_id_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='horas_trabajadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
