# Generated by Django 4.1 on 2022-12-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_proyectos_cancelar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='rechazar',
            field=models.TextField(null=True),
        ),
    ]
