# Generated by Django 4.1 on 2022-09-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_estado_usuario_profile_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
