# Generated by Django 4.1 on 2022-10-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userstory_horas_trabajadas_alter_sprint_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='horas_trabajadas',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
