# Generated by Django 4.1 on 2022-12-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userstory_rechazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='cancel',
            field=models.TextField(null=True),
        ),
    ]
