# Generated by Django 4.1 on 2022-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_sprint_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='cancelar',
            field=models.TextField(null=True),
        ),
    ]
