# Generated by Django 4.1 on 2022-09-08 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_alter_proyectos_estado_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='id_proyecto',
        ),
        migrations.RemoveField(
            model_name='miembros',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='miembros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
