# Generated by Django 4.0.1 on 2022-10-17 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_remove_userstory_horas_trabajadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='horas_trabajadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='horas_estimadas',
            field=models.IntegerField(default=0),
        ),
    ]
