# Generated by Django 4.0.1 on 2022-10-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_logestados_usuario_responsable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logproyectos',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
