# Generated by Django 4.1 on 2022-09-08 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_proyectos_miembro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='miembro',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='miembro',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
