# Generated by Django 4.0.1 on 2022-10-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_fecha_creacion_logproyectos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logproyectos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='logproyectos',
            name='fecha_creacion',
            field=models.TextField(null=True),
        ),
    ]
