# Generated by Django 4.0.1 on 2022-11-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_logproyectos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logestados',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logmiembro_sprint',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logmiembros',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logproyectos',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logrol',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logsprint',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logtipo_user_story',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='loguserstory',
            name='descripcion_accion',
            field=models.CharField(max_length=2000),
        ),
    ]
