# Generated by Django 4.1 on 2022-09-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_proyectos_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=11),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
