# Generated by Django 4.0.1 on 2022-11-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_logestados_descripcion_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logestados',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logmiembro_sprint',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logmiembros',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logproyectos',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logrol',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logsprint',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='logtipo_user_story',
            name='descripcion_accion',
        ),
        migrations.RemoveField(
            model_name='loguserstory',
            name='descripcion_accion',
        ),
        migrations.AddField(
            model_name='logestados',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmiembro_sprint',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logmiembros',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logproyectos',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logrol',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logsprint',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logtipo_user_story',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loguserstory',
            name='descripcion_action',
            field=models.CharField(default=' ', max_length=10000),
            preserve_default=False,
        ),
    ]
