# Generated by Django 4.0.1 on 2022-11-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_logestados_descripcion_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproyectos',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos'),
        ),
    ]
