# Generated by Django 4.1 on 2022-09-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_proyectos_estado_proyecto_alter_proyectos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='pendiente', max_length=11),
        ),
    ]
