# Generated by Django 4.1 on 2022-09-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_miembros_id_proyecto_and_more'),
        ('account', '0014_alter_proyectos_estado_proyecto'),
    ]

    operations = [
    ]
