# Generated by Django 4.1 on 2022-09-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_merge_20220909_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='miembros',
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='estado_proyecto',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Iniciado', 'Iniciado'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=11),
        ),
        migrations.DeleteModel(
            name='Miembros',
        ),
    ]
