# Generated by Django 4.1 on 2022-09-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_proyectos_miembros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.proyectos')),
                ('id_rol', models.ManyToManyField(to='account.roles')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usuarios')),
            ],
        ),
    ]
