# Generated by Django 4.1 on 2022-09-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_miembros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='miembro',
        ),
        migrations.AlterField(
            model_name='miembros',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
