# Generated by Django 4.1 on 2022-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_proyectos_miembro_alter_miembros_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.PositiveSmallIntegerField(blank=True, choices=[('Administrador', 'Administrador'), ('Product_Owner', 'Product Owner'), ('Scrum_Master', 'Scrum Master'), ('Developer_Team', 'Developer Team')], null=True)),
                ('desc_rol', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='miembros',
            name='id_rol',
            field=models.ManyToManyField(to='account.rol'),
        ),
    ]
