# Generated by Django 4.1 on 2022-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rol_delete_roles_alter_miembros_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Product_Owner', 'Product Owner'), ('Scrum_Master', 'Scrum Master'), ('Developer_Team', 'Developer Team')], max_length=20, null=True),
        ),
    ]
