# Generated by Django 4.1 on 2022-09-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0020_alter_rol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
