# Generated by Django 4.1 on 2022-09-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rol_permisos_alter_rol_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
