# Generated by Django 4.1 on 2022-09-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_miembros_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros',
            name='id_rol',
        ),
        migrations.AlterField(
            model_name='miembros',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
