# Generated by Django 4.1 on 2022-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_miembros_id_rol_alter_miembros_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembros',
            name='id_rol',
            field=models.ManyToManyField(to='account.rol'),
        ),
    ]
