# Generated by Django 4.1 on 2022-09-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_miembros_id_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='com_us',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='historial_us',
        ),
        migrations.AddField(
            model_name='sprint',
            name='duracion_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstory',
            name='horas_estimadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Terminado', 'Terminado')], default='Iniciado', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad_us',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.tipous'),
        ),
        migrations.CreateModel(
            name='Miembro_Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajo', models.BigIntegerField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.miembros')),
            ],
        ),
        migrations.AddField(
            model_name='userstory',
            name='encargado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.miembro_sprint'),
        ),
    ]
