# Generated by Django 4.1 on 2022-09-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_sprint_fecha_fin_remove_userstory_com_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracion_dias',
            field=models.IntegerField(null=True),
        ),
    ]
