# Generated by Django 4.1 on 2022-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_sprint_duracion_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
