# Generated by Django 4.1 on 2022-09-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
