# Generated by Django 4.1 on 2022-09-25 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_sprint',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usuarios'),
        ),
    ]
