# Generated by Django 4.1 on 2022-09-25 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0031_alter_miembro_sprint_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro_sprint',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
