# Generated by Django 4.1 on 2022-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_sprint_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
