# Generated by Django 4.1 on 2022-09-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_sprint_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proyectos'),
        ),
    ]
